name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01bb8313adeb5ff2b358ec5f3af37569a0f87edcfdb15192adab4df881f7199e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
