name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2959e99e9e3bdeb87ecbcebc89ce74f11dbfd23cf34b83f9068b852fc33766af"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
