name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e76a2f4594a4fd56d475de4a7d6c1e1dbc1d3878fcf09be424cc8c5529e5af0f"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
