name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7254587ea90c061b765449c8c10f5dcb74f8a064cc7cab7112f5148b9c5d3cad"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
