name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e490c82a1e28b5d7b5e0cd2e10a2edb3df20a270bfb762905f89488bcb21238"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
