name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7dd481256bdf1eed8abf9acd7a24122b98bb40a4349802258241c3f6bad06d7"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
