name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9b66d1c54891ff9bb5f3425ad9a3daafa2c54059a19e9ab26648dcba14a06db"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
