name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90326eadfbc85d17eaee6220ad8846afc2a37f9776843ae8b6bac68849dcdd50"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
