name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed78414aea18decf924d23c949b2526173da1faa37872e412116de90a7ced1fe"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
