name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51b80dfc933245d3ca0b98f6aa746e679fa4fb486068e8aeca439b1e69784a38"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
