name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4e3cd04859ab80ff48cbcd3748232c1cbc79f7fc0ac9f59210b450d69320c94"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
