name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "83555e55afb801952ba70fa0a064d3afb65609ee1491f8e394bbb5aee0f69522"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
