name = "Project CBT"
author = "Nrmot"
version = "Nightly"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0878fd0c222d8b98687977dad53bf5327095432c9254a00a1d57b497a16e048c"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
