name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1580131b64b86c94ceafde488c447be602c015d7766ed1e6cc814e4e52454a0f"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
