name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "342dd74d5d8bfc18f6c12c2a4aac687cab5b441f027f5fab6c6d1feea2649060"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
