name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed4c139ef26e77709aa4c81e9d7d4725f5a4611b98f24d4ff66e13068cc75469"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
