name = "Project CBT"
author = "Nrmot"
version = "DEV"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "269e836fd3a63fc07c96f2c9aa595c120f09b2fc34f152f9fad32b0762d25735"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
